import Chair from '../../assets/images/chair.png'

export const productList = [
  {
    id: 1,
    title: '인테리어 가구',
    subTitle: '마르셀 브로이어 바실리 체어 Marcel Breuer Wassily',
    status: '대기중',
    date: '2022.12.30에 등록',
    fileSize: '9,999GB · GLTF',
    picture: Chair,
  },
  {
    id: 2,
    title: '인테리어 가구',
    subTitle: '마르셀 브로이어 바실리 체어 Marcel Breuer Wassily',
    status: '대기중',
    date: '2022.12.30에 등록',
    fileSize: '9,999GB · GLTF',
    picture: Chair,
  },
  {
    id: 3,
    title: '인테리어 가구',
    subTitle: '마르셀 브로이어 바실리 체어 Marcel Breuer Wassily',
    status: '대기중',
    date: '2022.12.30에 등록',
    fileSize: '9,999GB · GLTF',
    picture: Chair,
  },
  {
    id: 4,
    title: '인테리어 가구',
    subTitle: '마르셀 브로이어 바실리 체어 Marcel Breuer Wassily',
    status: '대기중',
    date: '2022.12.30에 등록',
    fileSize: '9,999GB · GLTF',
    picture: Chair,
  },
  {
    id: 5,
    title: '인테리어 가구',
    subTitle: '마르셀 브로이어 바실리 체어 Marcel Breuer Wassily',
    status: '대기중',
    date: '2022.12.30에 등록',
    fileSize: '9,999GB · GLTF',
    picture: Chair,
  },
  {
    id: 6,
    title: '인테리어 가구',
    subTitle: '마르셀 브로이어 바실리 체어 Marcel Breuer Wassily',
    status: '대기중',
    date: '2022.12.30에 등록',
    fileSize: '9,999GB · GLTF',
    picture: Chair,
  },
  {
    id: 7,
    title: '인테리어 가구',
    subTitle: '마르셀 브로이어 바실리 체어 Marcel Breuer Wassily',
    status: '대기중',
    date: '2022.12.30에 등록',
    fileSize: '9,999GB · GLTF',
    picture: Chair,
  },
]

export const distributionListData = [
  {
    id: 1,
    stayTime: '0초',
    numberOfVisits: 3333,
    ratio: 80,
  },
  {
    id: 2,
    stayTime: '1초 - 10초',
    numberOfVisits: 200,
    ratio: 60,
  },
  {
    id: 3,
    stayTime: '11초 - 30초',
    numberOfVisits: 500,
    ratio: 40,
  },
  {
    id: 4,
    stayTime: '31초 - 1분',
    numberOfVisits: 400,
    ratio: 30,
  },
  {
    id: 5,
    stayTime: '1분 - 2분',
    numberOfVisits: 600,
    ratio: 25,
  },
  {
    id: 6,
    stayTime: '2분 - 4분',
    numberOfVisits: 250,
    ratio: 15,
  },
  {
    id: 7,
    stayTime: '4분 - 8분',
    numberOfVisits: 280,
    ratio: 5,
  },
]

export const AverageListData = [
  {
    id: 1,
    date: '2022.12.30',
    averageStayTime: '33초',
    numberOfVisits: 3333,
    totalStayTime: '33시간 33분 33초',
  },
  {
    id: 2,
    date: '2022.12.30',
    averageStayTime: '33초',
    numberOfVisits: 3333,
    totalStayTime: '33시간 33분 33초',
  },
  {
    id: 3,
    date: '2022.12.30',
    averageStayTime: '33초',
    numberOfVisits: 3333,
    totalStayTime: '33시간 33분 33초',
  },
  {
    id: 4,
    date: '2022.12.30',
    averageStayTime: '33초',
    numberOfVisits: 3333,
    totalStayTime: '33시간 33분 33초',
  },
  {
    id: 5,
    date: '2022.12.30',
    averageStayTime: '33초',
    numberOfVisits: 3333,
    totalStayTime: '33시간 33분 33초',
  },
  {
    id: 6,
    date: '2022.12.30',
    averageStayTime: '33초',
    numberOfVisits: 3333,
    totalStayTime: '33시간 33분 33초',
  },
  {
    id: 7,
    date: '2022.12.30',
    averageStayTime: '33초',
    numberOfVisits: 3333,
    totalStayTime: '33시간 33분 33초',
  },
]
